language: ruby

rvm:
  - 2.7.0

services:
  - postgresql

script:
  - bundle config set deployment 'true'
  - bundle install
  - bundle exec bin/rails db:create
  - bundle exec bin/rails db:migrate
  - bundle exec rspec
