language: ruby

rvm:
  - 2.7.0

services:
  - postgresql

dist: trusty

addons:
  postgresql: "9.4"

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

install:
  - bundle _1.17.3_ install
  - nvm install 11.10.0
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec bin/rails db:create
  - bundle exec bin/rails db:migrate
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle exec rspec
