language: ruby

rvm:
  - 2.7.0

services:
  - postgresql

dist: trusty

script:
  - gem install bundler:1.17.3
  # - bundle config set deployment 'true'
  - bundle install 
  - bundle exec bin/rails db:create
  - bundle exec bin/rails db:migrate
  - bundle exec rspec
